# Generated by protoc-gen-pcpy. DO NOT EDIT.
import protocache as _pc


class Mode:
    MODE_A = 0
    MODE_B = 1
    MODE_C = 2


class Small(_pc.Message):
    _field_i32 = 0
    _field_flag = 1
    _field_str = 3


class Vec2D_Vec1D(_pc.Array):
    TYPE = (_pc.NONE, _pc.F32, None)


class Vec2D(_pc.Array):
    TYPE = (_pc.NONE, _pc.ARRAY, Vec2D_Vec1D)


class ArrMap_Array(_pc.Array):
    TYPE = (_pc.NONE, _pc.F32, None)


class ArrMap(_pc.Map):
    TYPE = (_pc.STRING, _pc.ARRAY, ArrMap_Array)


class Main(_pc.Message):
    _field_i32 = 0
    _field_u32 = 1
    _field_i64 = 2
    _field_u64 = 3
    _field_flag = 4
    _field_mode = 5
    _field_str = 6
    _field_data = 7
    _field_f32 = 8
    _field_f64 = 9
    _field_object = 10
    _field_i32v = 11
    _field_u64v = 12
    _field_strv = 13
    _field_datav = 14
    _field_f32v = 15
    _field_f64v = 16
    _field_flags = 17
    _field_objectv = 18
    _field_t_u32 = 19
    _field_t_i32 = 20
    _field_t_s32 = 21
    _field_t_u64 = 22
    _field_t_i64 = 23
    _field_t_s64 = 24
    _field_index = 25
    _field_objects = 26
    _field_matrix = 27
    _field_vector = 28
    _field_arrays = 29
    _field_modev = 31


class CyclicA(_pc.Message):
    _field_value = 0
    _field_cyclic = 1


class CyclicB(_pc.Message):
    _field_value = 0
    _field_cyclic = 1


class Deprecated_Valid(_pc.Message):
    _field_val = 0


class Deprecated(_pc.Message):
    pass

Small._schema = (
    ("i32", Small._field_i32, False, _pc.NONE, _pc.I32, None),
    ("flag", Small._field_flag, False, _pc.NONE, _pc.BOOL, None),
    ("str", Small._field_str, False, _pc.NONE, _pc.STRING, None),
)

Main._schema = (
    ("i32", Main._field_i32, False, _pc.NONE, _pc.I32, None),
    ("u32", Main._field_u32, False, _pc.NONE, _pc.U32, None),
    ("i64", Main._field_i64, False, _pc.NONE, _pc.I64, None),
    ("u64", Main._field_u64, False, _pc.NONE, _pc.U64, None),
    ("flag", Main._field_flag, False, _pc.NONE, _pc.BOOL, None),
    ("mode", Main._field_mode, False, _pc.NONE, _pc.ENUM, None),
    ("str", Main._field_str, False, _pc.NONE, _pc.STRING, None),
    ("data", Main._field_data, False, _pc.NONE, _pc.BYTES, None),
    ("f32", Main._field_f32, False, _pc.NONE, _pc.F32, None),
    ("f64", Main._field_f64, False, _pc.NONE, _pc.F64, None),
    ("object", Main._field_object, False, _pc.NONE, _pc.MESSAGE, Small),
    ("i32v", Main._field_i32v, True, _pc.NONE, _pc.I32, None),
    ("u64v", Main._field_u64v, True, _pc.NONE, _pc.U64, None),
    ("strv", Main._field_strv, True, _pc.NONE, _pc.STRING, None),
    ("datav", Main._field_datav, True, _pc.NONE, _pc.BYTES, None),
    ("f32v", Main._field_f32v, True, _pc.NONE, _pc.F32, None),
    ("f64v", Main._field_f64v, True, _pc.NONE, _pc.F64, None),
    ("flags", Main._field_flags, True, _pc.NONE, _pc.BOOL, None),
    ("objectv", Main._field_objectv, True, _pc.NONE, _pc.MESSAGE, Small),
    ("t_u32", Main._field_t_u32, False, _pc.NONE, _pc.U32, None),
    ("t_i32", Main._field_t_i32, False, _pc.NONE, _pc.I32, None),
    ("t_s32", Main._field_t_s32, False, _pc.NONE, _pc.I32, None),
    ("t_u64", Main._field_t_u64, False, _pc.NONE, _pc.U64, None),
    ("t_i64", Main._field_t_i64, False, _pc.NONE, _pc.I64, None),
    ("t_s64", Main._field_t_s64, False, _pc.NONE, _pc.I64, None),
    ("index", Main._field_index, True, _pc.STRING, _pc.I32, None),
    ("objects", Main._field_objects, True, _pc.I32, _pc.MESSAGE, Small),
    ("matrix", Main._field_matrix, False, _pc.NONE, _pc.ARRAY, Vec2D),
    ("vector", Main._field_vector, True, _pc.NONE, _pc.MAP, ArrMap),
    ("arrays", Main._field_arrays, False, _pc.NONE, _pc.MAP, ArrMap),
    ("modev", Main._field_modev, True, _pc.NONE, _pc.ENUM, None),
)

CyclicA._schema = (
    ("value", CyclicA._field_value, False, _pc.NONE, _pc.I32, None),
    ("cyclic", CyclicA._field_cyclic, False, _pc.NONE, _pc.MESSAGE, CyclicB),
)

CyclicB._schema = (
    ("value", CyclicB._field_value, False, _pc.NONE, _pc.I32, None),
    ("cyclic", CyclicB._field_cyclic, False, _pc.NONE, _pc.MESSAGE, CyclicA),
)

Deprecated_Valid._schema = (
    ("val", Deprecated_Valid._field_val, False, _pc.NONE, _pc.I32, None),
)

Deprecated._schema = ()
